name: Deploy with Nginx Load Balancer

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/node_app_ci_test:latest .

      - name: Push Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/node_app_ci_test:latest

      # Deploy to EC2-1
      - name: Deploy to EC2-1
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.NODE_APP_EC2_SERVER_1 }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY_1 }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/node_app_ci_test:latest
            docker stop node_app_ci_testContainer || true
            docker rm node_app_ci_testContainer|| true
            docker run -d -p 8080:8080 --name node_app_ci_testContainer ${{ secrets.DOCKER_USERNAME }}/node_app_ci_test:latest

      # Deploy to EC2-2
      - name: Deploy to EC2-2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.NODE_APP_EC2_SERVER_2 }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY_2 }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/node_app_ci_test:latest
            docker stop node_app_ci_testContainer || true
            docker rm node_app_ci_testContainer || true
            docker run -d -p 8080:8080 --name node_app_ci_testContainer ${{ secrets.DOCKER_USERNAME }}/node_app_ci_test:latest